# vim: ts=2 sw=2 expandtab ai
---
subscription_repos:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-ose-3.6-rpms
  - rhel-7-fast-datapath-rpms
docker_storage_dev: /dev/xvdb

rhel_install_packages:
  - docker
  - dnsmasq
  - python-docker-py
  - skopeo
  - cockpit-docker
  - etcd
  - flannel

rhel_seed_images_nodes: "{{ rhel_seed_images_enterprise_nodes if openshift_deployment_type == 'openshift-enterprise' else rhel_seed_images_origin_nodes }}"
rhel_seed_images_masters: "{{ rhel_seed_images_enterprise_masters if openshift_deployment_type == 'openshift-enterprise' else rhel_seed_images_origin_masters }}"
rhel_seed_images_infra: "{{ rhel_seed_images_enterprise_infra if openshift_deployment_type == 'openshift-enterprise' else rhel_seed_images_origin_infra }}"
rhel_seed_images_origin_nodes: []
rhel_seed_images_origin_masters: []
rhel_seed_images_origin_infra: []

rhel_seed_images_enterprise_nodes:
  - "registry.access.redhat.com/openshift3/node:{{ openshift_image_tag }}"
  - "registry.access.redhat.com/openshift3/openvswitch:{{ openshift_image_tag }}"

rhel_seed_images_enterprise_masters:
  - "registry.access.redhat.com/openshift3/ose:{{ openshift_image_tag }}"
  - "registry.access.redhat.com/rhel7/etcd:latest"

rhel_seed_images_enterprise_infra:
  - "registry.access.redhat.com/openshift3/logging-auth-proxy:v{{ openshift_release }}"
  - "registry.access.redhat.com/openshift3/logging-curator:v{{ openshift_release }}"
  - "registry.access.redhat.com/openshift3/logging-elasticsearch:v{{ openshift_release }}"
  - "registry.access.redhat.com/openshift3/logging-fluentd:v{{ openshift_release }}"
  - "registry.access.redhat.com/openshift3/logging-kibana:v{{ openshift_release }}"
  - "registry.access.redhat.com/openshift3/metrics-cassandra:v{{ openshift_release }}"
  - "registry.access.redhat.com/openshift3/metrics-hawkular-metrics:v{{ openshift_release }}"
  - "registry.access.redhat.com/openshift3/metrics-heapster:v{{ openshift_release }}"
  - "registry.access.redhat.com/openshift3/ose-deployer:{{ openshift_image_tag }}"
  - "registry.access.redhat.com/openshift3/ose-docker-registry:{{ openshift_image_tag }}"
  - "registry.access.redhat.com/openshift3/ose-haproxy-router:{{ openshift_image_tag }}"
  - "registry.access.redhat.com/openshift3/ose-pod:{{ openshift_image_tag }}"
  - "registry.access.redhat.com/openshift3/ose-service-catalog:v{{ openshift_release }}"
  - "registry.access.redhat.com/openshift3/registry-console:v{{ openshift_release }}"
  - "registry.access.redhat.com/rhgs3/rhgs-gluster-block-prov-rhel7:latest"
  - "registry.access.redhat.com/rhgs3/rhgs-server-rhel7:latest"
  - "registry.access.redhat.com/rhgs3/rhgs-volmanager-rhel7:latest"
