# vim: ts=2 sw=2 expandtab ai
---
- name: get EC2 instances
  any_errors_fatal: true
  force_handlers: true
  hosts: ec2
  gather_facts: false
  connection: local
  tags: [ ec2 ]
  roles:
    - ec2

- name: post configure for CNS
  any_errors_fatal: true
  force_handlers: true
  hosts: storage
  gather_facts: true
  tags: [ cns ]
  tasks:
    - name: create template for gluster endpoints
      connection: local
      run_once: true
      template:
        src: gluster-cluster.yml.j2
        dest: /tmp/gluster-cluster.yml

    - name: import gluster endpoints
      connection: local
      run_once: true
      register: oc_out
      failed_when: "oc_out.rc != 0 and 'AlreadyExists' not in oc_out.stderr"
      changed_when: oc_out.rc == 0 
      command: /usr/bin/oc create -f /tmp/gluster-cluster.yml

    - name: determine clusterid
      connection: local
      run_once: true
      uri:
        url: "http://heketi-storage.{{ openshift_master_default_subdomain }}/clusters"
        return_content: true
      register: clusterid_out

    - name: set clusterid
      connection: local
      run_once: true
      set_fact:
        heketi_clusterid: "{{ clusterid_out.json.clusters | first }}"

    - name: write out storageclass file
      connection: local
      run_once: true
      template:
        src: cns-storageclass.yml.j2
        dest: /tmp/cns-storageclass.yml

    - name: import storagelcass
      connection: local
      run_once: true
      register: oc_out
      failed_when: "oc_out.rc != 0 and 'AlreadyExists' not in oc_out.stderr"
      changed_when: oc_out.rc == 0 
      command: /usr/bin/oc create -f /tmp/cns-storageclass.yml
