# vim: ts=2 sw=2 expandtab ai
---
- name: Create EC2 instances
  any_errors_fatal: true
  force_handlers: true
  hosts: ec2
  gather_facts: false
  connection: local
  tags: ec2
  vars:
    ec2_create: true
  roles:
    - ec2

- name: configure local environment to see hosts
  any_errors_fatal: true
  force_handlers: true
  hosts: ec2
  gather_facts: false
  connection: local
  tags: [ always ]
  roles: [ localconfig ]
