# vim: ts=2 sw=2 expandtab ai
---
- name: read in secret vars
  any_errors_fatal: true
  hosts: all
  gather_facts: false
  connection: local
  tags: [ always ]
  tasks: 
  - include_vars: "{{ SECRETS }}"
    when: SECRETS is defined
    run_once: true


- name: Create EC2 instances
  any_errors_fatal: true
  force_handlers: true
  hosts: ec2
  gather_facts: false
  connection: local
  tags: ec2
  vars:
    ec2_create: true
  roles:
    - ec2

- name: add instances to ssh config
  any_errors_fatal: true
  force_handlers: true
  hosts: all
  gather_facts: false
  connection: local
  tags: [ always ]
  roles: [ sshconfig ]
