# vim: ts=2 sw=2 expandtab ai
---
- name: get EC2 instances
  any_errors_fatal: true
  force_handlers: true
  hosts: ec2
  gather_facts: false
  connection: local
  tags: [ ec2 ]
  roles:
    - ec2

- name: Install Openshift
  import_playbook: ./openshift-ansible/playbooks/byo/config.yml
