# vim: ts=2 sw=2 expandtab ai
---

- name: post configuration - setup users and local cli
  any_errors_fatal: true
  force_handlers: true
  hosts: masters
  gather_facts: true
  roles:
    - postconfig

  tasks:

    - debug:
        var: post_msg
      tags: [ always ]
      run_once: true
      vars:
        post_msg:
          "CA Certificate": "{{ post_certserv_url }}"
          "OCP Console": "{{ post_ocp_url }}"
