# vim: ts=2 sw=2 expandtab ai
---
default_ec2_drive_map:
  - /dev/sda1
  - /dev/xvdb
  - /dev/xvdc

default_ec2_volumes:
  - delete_on_termination: true
    device_name: '{{ ec2_drive_map.0 }}'
    volume_size: 20
    volume_type: gp2
  - delete_on_termination: true
    device_name: '{{ ec2_drive_map.1 }}'
    volume_size: 20
    volume_type: gp2
  - delete_on_termination: true
    device_name: '{{ ec2_drive_map.2 }}'
    volume_size: 20
    volume_type: gp2
