# vim: ts=2 sw=2 expandtab ai
---

- name: Wait for SSH to come up
  wait_for:
    host: "{{ ansible_host }}"
    port: 22
    # delay: 10
    timeout: 320
    state: started

- name: pausing 10 seconds to ensure ssh accepts connection (intermittent)
  pause:
    seconds: 10
  listen: Wait for SSH to come up

