# vim: ts=2 sw=2 expandtab ai
---

- name: add hosts to /etc/hosts file
  become: true
  run_once: true
  blockinfile:
    unsafe_writes: true
    state: "{{ sshconfig_clean | ternary('absent', 'present') }}"
    path: /etc/hosts
    block: |
      {% for hn in groups.all | sort %}
      {%   if hostvars[hn].public_ip | default('') | length > 0 %}
      {%     set app = '' if hn not in groups.dns else ocp_app_domain %}
      {%     set ocp = '' if hn not in groups.dns else ocp_hostname %}
      {{ hostvars[hn].public_ip }}     {{ hn }} {{ hostvars[hn].hostname }} {{ ocp }} {{ app }}
      {%   endif %}
      {% endfor %}
