# vim: ts=2 sw=2 expandtab ai
---

- set_fact:
    storage_devices: "{{ storage_devices | default([]) }}"

- include_tasks: config_ssh.yml
  tags: [ localconfig, local_ssh ]

- include_tasks: local_hosts.yml
  tags: [ localconfig, local_hosts ]

- include_tasks: make_ocp.yml
  tags: [ localconfig, local_ocp ]

- include_tasks: root_login.yml
  tags: [ localconfig, local_root ]

