# vim: ts=2 sw=2 expandtab ai
---

- name: clean up dynamically create OCP inventory
  run_once: true
  connection: local
  when: sshconfig_clean
  file:
    dest: inventory/demo.ocp
    state: absent

- name: dynamically create OCP inventory
  run_once: true
  connection: local
  when: not sshconfig_clean
  template:
    src: demo.ocp.j2
    dest: inventory/demo.ocp
