# vim: ts=2 sw=2 expandtab ai
---

- include_tasks: check_docker.yml
  when: ansible_pkg_mgr == 'atomic_container'
  tags: [ rhel, rhel_docker ]

- include_tasks: hostname.yml
  tags: [ rhel, rhel_hostname ]

- include_tasks: subscription.yml
  when: "ansible_distribution == 'RedHat'"
  tags: [ rhel, rhel_subscription ]

- include_tasks: services.yml
  tags: [ rhel, rhel_services ]

- include_tasks: dns.yml
  tags: [ rhel, rhel_dns ]

- include_tasks: storage.yml
  tags: [ rhel, rhel_storage ]

- include_tasks: test_dns.yml
  tags: [ rhel, rhel_test ]

- include_tasks: seed_docker.yml
  when: inventory_hostname in groups.nodes
  tags: [ rhek, rhel_seed ]

