# vim: ts=2 sw=2 expandtab ai
---

- name: ensure root can login
  become: true
  copy:
    src: "~{{ ansible_user }}/.ssh/authorized_keys"
    dest: "/root/.ssh/authorized_keys"
    remote_src: true
    owner: root
    group: root
    mode: 0600

- name: change ansible user to root
  set_fact:
    ansible_user: root
