# vim: ts=2 sw=2 expandtab ai
---
- name: register system
  redhat_subscription:
    state: present
    org_id: "{{ subscription_org }}"
    activationkey: "{{ subscription_ak }}"
  when: subscription_org is defined and subscription_ak is defined
  notify:
    - disable all repos
    - enable repos

- name: enable repos if needed
  meta: flush_handlers
