# vim: ts=2 sw=2 expandtab ai
---
- name: Ansible Service Broker - check if namespace exists
  run_once: true
  connection: local
  command: "/usr/bin/oc get project {{ ans }}"
  register: asb_out
  changed_when: ans_check in asb_out.stderr_lines

- include_tasks: asb_cleanup_tasks.yml
  when: asb_out is not changed
