# vim: ts=2 sw=2 expandtab ai
---
- name: remote copy admin config from root
  when: ansible_user != 'root'
  become: true
  command: "/usr/bin/cp -ar /root/.kube/ {{ ansible_user_dir }}/.kube/"

- name: remote set permissions on config
  when: ansible_user != 'root'
  become: true
  file:
    recurse: true
    group: "{{ ansible_user_id }}"
    owner: "{{ ansible_user_id }}"
    path: "{{ ansible_user_dir }}/.kube/"
