# vim: ts=2 sw=2 expandtab ai
---
- name: check AWS variables
  include_tasks: aws_check.yml
  tags: [ec2]

- name: lookup VPC or subnets, and define Security Group
  include_tasks: vpc_subnet_sg.yml
  when: ec2_create
  tags: [ec2]

- name: create or clean instances
  include_tasks: ec2_instances.yml
  tags: [ec2]
